# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_pathology', models.TextField(max_length=255, verbose_name='Sobre a patologia')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_nascimento', models.CharField(default='sem data', max_length=255, verbose_name='Data Nascimento')),
                ('adress', models.CharField(max_length=100, verbose_name='Endere\xe7o')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=50, verbose_name='Cep')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('mobile', models.CharField(max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('specialty', models.TextField(max_length=30, verbose_name='especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_nascimento', models.CharField(default='sem data', max_length=255, verbose_name='Data Nascimento')),
                ('adress', models.CharField(max_length=100, verbose_name='Endere\xe7o')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('cep', models.CharField(max_length=50, verbose_name='Cep')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('mobile', models.CharField(max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nemo.Medico', verbose_name='Medico responsavel'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nemo.Paciente', verbose_name='Paciente a ser consultado'),
        ),
    ]
