# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(default='', max_length=255, verbose_name='Data Nascimento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
