# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0002_auto_20171124_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
    ]
