# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemo', '0003_auto_20171124_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='data_nascimento',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Data Nascimento'),
        ),
    ]
